export type PhotoMetadata = {
  category: string;
  order: number;
  createdAt: string;
  sourceName: string;
};

export const PHOTO_METADATA: Record<string, PhotoMetadata> = {
  // academic
  "academic__all_subjects": {
    category: "academic",
    order: 1,
    createdAt: "2026-03-19T11:49:33",
    sourceName: "Academic_All Subjects.jpeg",
  },
  "academic__world_history": {
    category: "academic",
    order: 2,
    createdAt: "2026-03-19T11:49:35",
    sourceName: "Academic_World History.jpeg",
  },
  "academic__myanmar_history": {
    category: "academic",
    order: 3,
    createdAt: "2026-03-19T11:49:36",
    sourceName: "Academic_Myanmar History.jpeg",
  },
  "academic__anthropology": {
    category: "academic",
    order: 4,
    createdAt: "2026-03-19T11:49:40",
    sourceName: "Academic_Anthropology.jpeg",
  },
  "academic__earth_science": {
    category: "academic",
    order: 5,
    createdAt: "2026-03-19T11:49:40",
    sourceName: "Academic_Earth Science.jpeg",
  },
  "academic__geography": {
    category: "academic",
    order: 6,
    createdAt: "2026-03-19T11:49:40",
    sourceName: "Academic_Geography.jpeg",
  },
  "academic__religion_history": {
    category: "academic",
    order: 7,
    createdAt: "2026-03-19T11:49:41",
    sourceName: "Academic_Religion History.jpeg",
  },
  "academic__business_overview": {
    category: "academic",
    order: 8,
    createdAt: "2026-03-19T11:49:42",
    sourceName: "Academic_Business Overview.jpeg",
  },
  "academic__political_science": {
    category: "academic",
    order: 9,
    createdAt: "2026-03-19T11:49:43",
    sourceName: "Academic_Political Science.jpeg",
  },
  "academic__mathematics": {
    category: "academic",
    order: 10,
    createdAt: "2026-03-19T11:49:44",
    sourceName: "Academic_Mathematics_2.jpeg",
  },
  "academic__art": {
    category: "academic",
    order: 11,
    createdAt: "2026-03-19T11:49:47",
    sourceName: "Academic_Art.jpeg",
  },
  "academic__literature": {
    category: "academic",
    order: 12,
    createdAt: "2026-03-19T11:49:48",
    sourceName: "Academic_Literature.jpeg",
  },
  "academic__chemistry": {
    category: "academic",
    order: 13,
    createdAt: "2026-03-19T11:49:50",
    sourceName: "Academic_Chemistry.jpeg",
  },
  "academic__physics": {
    category: "academic",
    order: 14,
    createdAt: "2026-03-19T11:49:50",
    sourceName: "Academic_Physics.png",
  },
  "academic__microbiology": {
    category: "academic",
    order: 15,
    createdAt: "2026-03-19T11:49:51",
    sourceName: "Academic_Microbiology.jpeg",
  },
  "academic__tech_biography": {
    category: "academic",
    order: 16,
    createdAt: "2026-03-19T11:49:54",
    sourceName: "Academic_Tech Biography.jpeg",
  },
  "academic__economics": {
    category: "academic",
    order: 17,
    createdAt: "2026-03-19T11:49:56",
    sourceName: "Academic_Economics.jpeg",
  },
  "academic__local_biography": {
    category: "academic",
    order: 18,
    createdAt: "2026-03-19T11:49:56",
    sourceName: "Academic_Local Biography.jpeg",
  },

  // author
  "author__my_jobs": {
    category: "author",
    order: 1,
    createdAt: "2026-03-19T11:29:29",
    sourceName: "Author_My Jobs_2.jpeg",
  },
  "author__finance": {
    category: "author",
    order: 2,
    createdAt: "2026-03-19T11:29:32",
    sourceName: "Author_Finance_2.jpeg",
  },
  "author__my_diary": {
    category: "author",
    order: 3,
    createdAt: "2026-03-19T11:29:32",
    sourceName: "Author_My Diary_2.jpeg",
  },
  "author__my_philosophy": {
    category: "author",
    order: 4,
    createdAt: "2026-03-19T11:29:33",
    sourceName: "Author_My Philosophy.jpeg",
  },
  "author__my_girl": {
    category: "author",
    order: 5,
    createdAt: "2026-03-19T11:29:35",
    sourceName: "Author_My Girl.jpeg",
  },
  "author__my_home": {
    category: "author",
    order: 6,
    createdAt: "2026-03-19T11:29:38",
    sourceName: "Author_My Home.jpeg",
  },
  "author__travel_myanmar": {
    category: "author",
    order: 7,
    createdAt: "2026-03-19T11:29:39",
    sourceName: "Author_Travel - Myanmar.jpeg",
  },
  "author__gardening": {
    category: "author",
    order: 8,
    createdAt: "2026-03-19T11:29:41",
    sourceName: "Author_Gardening.jpeg",
  },
  "author__animals": {
    category: "author",
    order: 9,
    createdAt: "2026-03-19T11:29:43",
    sourceName: "Author_Animals.jpeg",
  },
  "author__drawing": {
    category: "author",
    order: 10,
    createdAt: "2026-03-19T11:29:44",
    sourceName: "Author_Drawing.jpeg",
  },
  "author__cooking": {
    category: "author",
    order: 11,
    createdAt: "2026-03-19T11:29:45",
    sourceName: "Author_Cooking.jpeg",
  },
  "author__relationship": {
    category: "author",
    order: 12,
    createdAt: "2026-03-19T11:29:45",
    sourceName: "Author_Relationship.jpeg",
  },
  "author__travel_thailand": {
    category: "author",
    order: 13,
    createdAt: "2026-03-19T11:30:21",
    sourceName: "Author_Travel - Thailand.jpeg",
  },
  "author__fitness_sports": {
    category: "author",
    order: 14,
    createdAt: "2026-03-19T11:30:23",
    sourceName: "Author_Fitness Sports.jpeg",
  },
  "author__alcohol_drugs": {
    category: "author",
    order: 15,
    createdAt: "2026-03-19T11:30:24",
    sourceName: "Author_Alcohol Drugs.jpeg",
  },
  "author__sewing_fashion": {
    category: "author",
    order: 16,
    createdAt: "2026-03-19T11:30:26",
    sourceName: "Author_Sewing Fashion.jpeg",
  },
  "author__guitar_singer": {
    category: "author",
    order: 17,
    createdAt: "2026-03-19T11:30:29",
    sourceName: "Author_Guitar Singer.jpeg",
  },
  "author__camp_and_hiking": {
    category: "author",
    order: 18,
    createdAt: "2026-03-19T11:30:30",
    sourceName: "Author_Camp & Hiking.jpeg",
  },
  "author__facebook_blog": {
    category: "author",
    order: 19,
    createdAt: "2026-03-19T11:30:32",
    sourceName: "Author_Facebook Blog.jpeg",
  },
  "author__soon_vietnam": {
    category: "author",
    order: 20,
    createdAt: "2026-03-19T11:30:52",
    sourceName: "Author_Soon - Vietnam.jpeg",
  },
  "author__chatgpt": {
    category: "author",
    order: 21,
    createdAt: "2026-03-19T11:30:59",
    sourceName: "Author_CHATGPT.jpeg",
  },

  // business
  "business__startup_business": {
    category: "business",
    order: 1,
    createdAt: "2026-03-19T11:35:54",
    sourceName: "Business_Startup Business.jpeg",
  },
  "business__research_and_development": {
    category: "business",
    order: 2,
    createdAt: "2026-03-19T11:35:56",
    sourceName: "Business_Research & Development.jpeg",
  },
  "business__sales": {
    category: "business",
    order: 3,
    createdAt: "2026-03-19T11:35:57",
    sourceName: "Business_Sales.jpeg",
  },
  "business__branding": {
    category: "business",
    order: 4,
    createdAt: "2026-03-19T11:35:58",
    sourceName: "Business_Branding.jpeg",
  },
  "business__customer_service": {
    category: "business",
    order: 5,
    createdAt: "2026-03-19T11:35:59",
    sourceName: "Business_Customer Service.jpeg",
  },
  "business__marketing": {
    category: "business",
    order: 6,
    createdAt: "2026-03-19T11:35:59",
    sourceName: "Business_Marketing.jpeg",
  },
  "business__accounting_and_finance": {
    category: "business",
    order: 7,
    createdAt: "2026-03-19T11:36:01",
    sourceName: "Business_Accounting & Finance.jpeg",
  },
  "business__finance_and_investment": {
    category: "business",
    order: 8,
    createdAt: "2026-03-19T11:36:02",
    sourceName: "Business_Finance & Investment.jpeg",
  },
  "business__human_resources": {
    category: "business",
    order: 9,
    createdAt: "2026-03-19T11:36:03",
    sourceName: "Business_Human Resources.png",
  },
  "business__logistics": {
    category: "business",
    order: 10,
    createdAt: "2026-03-19T11:36:04",
    sourceName: "Business_Logistics.jpeg",
  },
  "business__product_management": {
    category: "business",
    order: 11,
    createdAt: "2026-03-19T11:36:07",
    sourceName: "Business_Product Management.jpeg",
  },
  "business__project_management": {
    category: "business",
    order: 12,
    createdAt: "2026-03-19T11:36:07",
    sourceName: "Business_Project Management.jpeg",
  },
  "business__administration": {
    category: "business",
    order: 13,
    createdAt: "2026-03-19T11:36:08",
    sourceName: "Business_Administration.jpeg",
  },
  "business__legal_and_compliance": {
    category: "business",
    order: 14,
    createdAt: "2026-03-19T11:36:09",
    sourceName: "Business_Legal & Compliance.jpeg",
  },
  "business__public_relation": {
    category: "business",
    order: 15,
    createdAt: "2026-03-19T11:36:11",
    sourceName: "Business_Public Relation.jpeg",
  },
  "business__l_and_development": {
    category: "business",
    order: 16,
    createdAt: "2026-03-19T11:36:12",
    sourceName: "Business_L & Development.jpeg",
  },
  "business__quality_assurance": {
    category: "business",
    order: 17,
    createdAt: "2026-03-19T11:36:13",
    sourceName: "Business_Quality Assurance.jpeg",
  },
  "business__data_and_analytics": {
    category: "business",
    order: 18,
    createdAt: "2026-03-19T11:36:15",
    sourceName: "Business_Data & Analytics.jpeg",
  },
  "business__engineer": {
    category: "business",
    order: 19,
    createdAt: "2026-03-19T11:36:16",
    sourceName: "Business_Engineer.jpeg",
  },
  "business__business_game": {
    category: "business",
    order: 20,
    createdAt: "2026-03-19T11:36:17",
    sourceName: "Business_Business Game.jpeg",
  },
  "business__hotel_and_tourism": {
    category: "business",
    order: 21,
    createdAt: "2026-03-19T11:36:18",
    sourceName: "Business_Hotel & Tourism.jpeg",
  },
  "business__interior_designer": {
    category: "business",
    order: 22,
    createdAt: "2026-03-19T11:36:19",
    sourceName: "Business_Interior Designer.jpeg",
  },
  "business__career_advice": {
    category: "business",
    order: 23,
    createdAt: "2026-03-19T11:36:43",
    sourceName: "Business_Career Advice.jpeg",
  },
  "business__computer_science": {
    category: "business",
    order: 24,
    createdAt: "2026-03-19T11:36:44",
    sourceName: "Business_Computer Science_2.jpeg",
  },

  // computer_science
  "computer_science__ml": {
    category: "computer_science",
    order: 1,
    createdAt: "2026-03-19T11:38:32",
    sourceName: "ComputerScience_ML.jpeg",
  },
  "computer_science__python": {
    category: "computer_science",
    order: 2,
    createdAt: "2026-03-19T11:38:32",
    sourceName: "ComputerScience_Python.jpeg",
  },
  "computer_science__dsa": {
    category: "computer_science",
    order: 3,
    createdAt: "2026-03-19T11:38:34",
    sourceName: "ComputerScience_DSA.jpeg",
  },
  "computer_science__dev_op": {
    category: "computer_science",
    order: 4,
    createdAt: "2026-03-19T11:38:35",
    sourceName: "ComputerScience_DevOp.jpeg",
  },
  "computer_science__web": {
    category: "computer_science",
    order: 5,
    createdAt: "2026-03-19T11:38:35",
    sourceName: "ComputerScience_Web.jpeg",
  },
  "computer_science__os": {
    category: "computer_science",
    order: 6,
    createdAt: "2026-03-19T11:38:36",
    sourceName: "ComputerScience_OS.jpeg",
  },
  "computer_science__data_base": {
    category: "computer_science",
    order: 7,
    createdAt: "2026-03-19T11:38:38",
    sourceName: "ComputerScience_Data Base.jpeg",
  },
  "computer_science__software": {
    category: "computer_science",
    order: 8,
    createdAt: "2026-03-19T11:38:39",
    sourceName: "ComputerScience_Software.jpeg",
  },
  "computer_science__cyber_security": {
    category: "computer_science",
    order: 9,
    createdAt: "2026-03-19T11:38:40",
    sourceName: "ComputerScience_Cyber Security.jpeg",
  },
  "computer_science__mobile": {
    category: "computer_science",
    order: 10,
    createdAt: "2026-03-19T11:38:41",
    sourceName: "ComputerScience_Mobile.jpeg",
  },
  "computer_science__game": {
    category: "computer_science",
    order: 11,
    createdAt: "2026-03-19T11:38:42",
    sourceName: "ComputerScience_Game.jpeg",
  },
  "computer_science__home_work": {
    category: "computer_science",
    order: 12,
    createdAt: "2026-03-19T11:39:00",
    sourceName: "ComputerScience_HomeWork.jpeg",
  },
  "computer_science__data_science": {
    category: "computer_science",
    order: 13,
    createdAt: "2026-03-19T11:39:01",
    sourceName: "ComputerScience_Data Science.jpeg",
  },
  "computer_science__mathematics": {
    category: "computer_science",
    order: 14,
    createdAt: "2026-03-19T11:39:03",
    sourceName: "ComputerScience_Mathematics.jpeg",
  },
  "computer_science__c_plus_plus": {
    category: "computer_science",
    order: 15,
    createdAt: "2026-03-19T11:39:04",
    sourceName: "ComputerScience_C + +.jpeg",
  },
  "computer_science__missile_development": {
    category: "computer_science",
    order: 16,
    createdAt: "2026-03-19T11:39:06",
    sourceName: "ComputerScience_Missile Development.jpeg",
  },
  "computer_science__networking": {
    category: "computer_science",
    order: 17,
    createdAt: "2026-03-19T11:39:07",
    sourceName: "ComputerScience_Networking.jpeg",
  },

  // fiction
  "fiction__great_holiday": {
    category: "fiction",
    order: 1,
    createdAt: "2026-03-19T12:22:02",
    sourceName: "Fiction_Great Holiday.jpeg",
  },
  "fiction__the_very_first_love": {
    category: "fiction",
    order: 2,
    createdAt: "2026-03-19T12:22:03",
    sourceName: "Fiction_The Very First Love.jpeg",
  },
  "fiction__unexpected_moment": {
    category: "fiction",
    order: 3,
    createdAt: "2026-03-19T12:22:05",
    sourceName: "Fiction_Unexpected Moment.jpeg",
  },
  "fiction__first_taste_of_traveling": {
    category: "fiction",
    order: 4,
    createdAt: "2026-03-19T12:22:06",
    sourceName: "Fiction_First Taste Of Traveling.jpeg",
  },
  "fiction__why_are_we_here": {
    category: "fiction",
    order: 5,
    createdAt: "2026-03-19T12:22:07",
    sourceName: "Fiction_Why Are We Here?.jpeg",
  },
  "fiction__vietnam_solo_traveling": {
    category: "fiction",
    order: 6,
    createdAt: "2026-03-19T12:22:08",
    sourceName: "Fiction_Vietnam: Solo Traveling.jpeg",
  },
  "fiction__old_friends_reunion": {
    category: "fiction",
    order: 7,
    createdAt: "2026-03-19T12:22:09",
    sourceName: "Fiction_Old Friends Reunion.jpeg",
  },
  "fiction__the_mysterious_girl": {
    category: "fiction",
    order: 8,
    createdAt: "2026-03-19T12:22:11",
    sourceName: "Fiction_The Mysterious Girl.jpeg",
  },
  "fiction__living_on_the_edge": {
    category: "fiction",
    order: 9,
    createdAt: "2026-03-19T12:22:12",
    sourceName: "Fiction_Living On The Edge.jpeg",
  },
  "fiction__village_cafe_diaries": {
    category: "fiction",
    order: 10,
    createdAt: "2026-03-19T12:22:13",
    sourceName: "Fiction_Village Café Diaries.jpeg",
  },
  "fiction__the_trail_along_village": {
    category: "fiction",
    order: 11,
    createdAt: "2026-03-19T12:22:14",
    sourceName: "Fiction_The Trail Along Village.jpeg",
  },
  "fiction__crossroads_of_love": {
    category: "fiction",
    order: 12,
    createdAt: "2026-03-19T12:22:15",
    sourceName: "Fiction_Crossroads of Love.jpeg",
  },
  "fiction__she_married_yesterday": {
    category: "fiction",
    order: 13,
    createdAt: "2026-03-19T12:22:17",
    sourceName: "Fiction_She Married Yesterday.jpeg",
  },
  "fiction__nostalgic_moment": {
    category: "fiction",
    order: 14,
    createdAt: "2026-03-19T12:22:18",
    sourceName: "Fiction_Nostalgic Moment.jpeg",
  },
  "fiction__pages_written_in_silence": {
    category: "fiction",
    order: 15,
    createdAt: "2026-03-19T12:22:20",
    sourceName: "Fiction_Pages Written in Silence.jpeg",
  },
  "fiction__explore_new_journey": {
    category: "fiction",
    order: 16,
    createdAt: "2026-03-19T12:23:37",
    sourceName: "Fiction_Explore New Journey.jpg",
  },

  // language
  "language__ielts": {
    category: "language",
    order: 1,
    createdAt: "2026-03-19T12:16:03",
    sourceName: "Language_IELTS.jpeg",
  },
  "language__english": {
    category: "language",
    order: 2,
    createdAt: "2026-03-19T12:16:04",
    sourceName: "Language_English.jpeg",
  },
  "language__chinese_2": {
    category: "language",
    order: 3,
    createdAt: "2026-03-19T12:16:05",
    sourceName: "Language_Chinese_2.jpeg",
  },
  "language__chinese_3": {
    category: "language",
    order: 4,
    createdAt: "2026-03-19T12:16:06",
    sourceName: "Language_Chinese_3.jpeg",
  },
  "language__cantonese": {
    category: "language",
    order: 5,
    createdAt: "2026-03-19T12:16:07",
    sourceName: "Language_Cantonese.jpeg",
  },
  "language__burmese": {
    category: "language",
    order: 6,
    createdAt: "2026-03-19T12:16:08",
    sourceName: "Language_Burmese.jpeg",
  },
  "language__chinese_4": {
    category: "language",
    order: 7,
    createdAt: "2026-03-19T12:16:08",
    sourceName: "Language_Chinese_4.jpeg",
  },
  "language__burmese_2": {
    category: "language",
    order: 8,
    createdAt: "2026-03-19T12:16:10",
    sourceName: "Language_Burmese_2.jpeg",
  },
  "language__japanese": {
    category: "language",
    order: 9,
    createdAt: "2026-03-19T12:16:10",
    sourceName: "Language_Japanese.jpeg",
  },
  "language__japanese_2": {
    category: "language",
    order: 10,
    createdAt: "2026-03-19T12:16:12",
    sourceName: "Language_Japanese_2.jpeg",
  },
  "language__korean": {
    category: "language",
    order: 11,
    createdAt: "2026-03-19T12:16:12",
    sourceName: "Language_Korean.jpeg",
  },
  "language__korean_2": {
    category: "language",
    order: 12,
    createdAt: "2026-03-19T12:16:13",
    sourceName: "Language_Korean_2.jpeg",
  },

  // movie
  "movie__warcraft": {
    category: "movie",
    order: 1,
    createdAt: "2026-03-19T12:18:09",
    sourceName: "Movie_Warcraft.jpeg",
  },
  "movie__gta_san_andreas": {
    category: "movie",
    order: 2,
    createdAt: "2026-03-19T12:18:10",
    sourceName: "Movie_GTA San Andreas.jpeg",
  },
  "movie__resident_evil": {
    category: "movie",
    order: 3,
    createdAt: "2026-03-19T12:18:10",
    sourceName: "Movie_Resident Evil.jpeg",
  },
  "movie__call_of_duty": {
    category: "movie",
    order: 4,
    createdAt: "2026-03-19T12:18:12",
    sourceName: "Movie_Call Of Duty.jpeg",
  },
  "movie__shadow_of_rome": {
    category: "movie",
    order: 5,
    createdAt: "2026-03-19T12:18:12",
    sourceName: "Movie_Shadow Of Rome.jpeg",
  },
  "movie__sims_play": {
    category: "movie",
    order: 6,
    createdAt: "2026-03-19T12:18:14",
    sourceName: "Movie_Sims Play.jpeg",
  },
  "movie__heroes": {
    category: "movie",
    order: 7,
    createdAt: "2026-03-19T12:18:15",
    sourceName: "Movie_Heroes.jpeg",
  },
  "movie__identity_v": {
    category: "movie",
    order: 8,
    createdAt: "2026-03-19T12:18:15",
    sourceName: "Movie_Identity V.jpeg",
  },
  "movie__x_men": {
    category: "movie",
    order: 9,
    createdAt: "2026-03-19T12:18:16",
    sourceName: "Movie_X Men.jpeg",
  },
  "movie__twilight_eclipse": {
    category: "movie",
    order: 10,
    createdAt: "2026-03-19T12:18:17",
    sourceName: "Movie_Twilight (Eclipse).jpeg",
  },
  "movie__vampire_diaries": {
    category: "movie",
    order: 11,
    createdAt: "2026-03-19T12:18:18",
    sourceName: "Movie_Vampire Diaries.jpeg",
  },
  "movie__harry_potter": {
    category: "movie",
    order: 12,
    createdAt: "2026-03-19T12:18:20",
    sourceName: "Movie_Harry Potter.jpeg",
  },
  "movie__w2_world": {
    category: "movie",
    order: 13,
    createdAt: "2026-03-19T12:18:20",
    sourceName: "Movie_W2 World.jpeg",
  },
  "movie__lord_of_the_rings": {
    category: "movie",
    order: 14,
    createdAt: "2026-03-19T12:18:21",
    sourceName: "Movie_Lord Of The Rings.jpeg",
  },
  "movie__game_of_thone": {
    category: "movie",
    order: 15,
    createdAt: "2026-03-19T12:18:22",
    sourceName: "Movie_Game Of Thone.jpeg",
  },
  "movie__hunger_games": {
    category: "movie",
    order: 16,
    createdAt: "2026-03-19T12:18:23",
    sourceName: "Movie_Hunger Games.jpeg",
  },
  "movie__maze_runner": {
    category: "movie",
    order: 17,
    createdAt: "2026-03-19T12:18:24",
    sourceName: "Movie_Maze Runner.jpeg",
  },
  "movie__squid_game": {
    category: "movie",
    order: 18,
    createdAt: "2026-03-19T12:18:25",
    sourceName: "Movie_Squid Game.jpeg",
  },
  "movie__avartar": {
    category: "movie",
    order: 19,
    createdAt: "2026-03-19T12:18:26",
    sourceName: "Movie_Avartar.jpeg",
  },
  "movie__inception": {
    category: "movie",
    order: 20,
    createdAt: "2026-03-19T12:18:27",
    sourceName: "Movie_Inception.jpeg",
  },
  "movie__friend_zone": {
    category: "movie",
    order: 21,
    createdAt: "2026-03-19T12:18:28",
    sourceName: "Movie_Friend Zone.jpeg",
  },
  "movie__the_innocent_man": {
    category: "movie",
    order: 22,
    createdAt: "2026-03-19T12:18:29",
    sourceName: "Movie_The Innocent Man.jpeg",
  },
  "movie__coming_soon": {
    category: "movie",
    order: 23,
    createdAt: "2026-03-19T12:18:30",
    sourceName: "Movie_Coming Soon.jpeg",
  },

  // projects
  "projects__book_mark": {
    category: "projects",
    order: 1,
    createdAt: "2026-03-19T12:25:58",
    sourceName: "Projects_Book Mark.jpeg",
  },
  "projects__doctor": {
    category: "projects",
    order: 2,
    createdAt: "2026-03-19T12:26:00",
    sourceName: "Projects_Doctor.jpeg",
  },
  "projects__accounting": {
    category: "projects",
    order: 3,
    createdAt: "2026-03-19T12:26:03",
    sourceName: "Projects_Accounting.jpeg",
  },
  "projects__dentist": {
    category: "projects",
    order: 4,
    createdAt: "2026-03-19T12:26:03",
    sourceName: "Projects_Dentist.jpeg",
  },
  "projects__mba_thesis": {
    category: "projects",
    order: 5,
    createdAt: "2026-03-19T12:26:04",
    sourceName: "Projects_MBA Thesis.jpeg",
  },
  "projects__pharmacy_store": {
    category: "projects",
    order: 6,
    createdAt: "2026-03-19T12:26:05",
    sourceName: "Projects_Pharmacy Store.jpeg",
  },
  "projects__travel_agency": {
    category: "projects",
    order: 7,
    createdAt: "2026-03-19T12:26:06",
    sourceName: "Projects_Travel Agency.jpeg",
  },
  "projects__corporate_triner": {
    category: "projects",
    order: 8,
    createdAt: "2026-03-19T12:26:08",
    sourceName: "Projects_Corporate Triner.jpeg",
  },
  "projects__wellax_pharma": {
    category: "projects",
    order: 9,
    createdAt: "2026-03-19T12:26:08",
    sourceName: "Projects_Wellax Pharma.jpeg",
  },
  "projects__transportation": {
    category: "projects",
    order: 10,
    createdAt: "2026-03-19T12:26:09",
    sourceName: "Projects_Transportation.jpeg",
  },
  "projects__casa_linda": {
    category: "projects",
    order: 11,
    createdAt: "2026-03-19T12:26:11",
    sourceName: "Projects_Casa Linda.jpeg",
  },
  "projects__street_food": {
    category: "projects",
    order: 12,
    createdAt: "2026-03-19T12:26:11",
    sourceName: "Projects_Street Food.jpeg",
  },
  "projects__colony_tea_house": {
    category: "projects",
    order: 13,
    createdAt: "2026-03-19T12:26:12",
    sourceName: "Projects_Colony Tea House.jpeg",
  },
  "projects__aqua_properties": {
    category: "projects",
    order: 14,
    createdAt: "2026-03-19T12:26:32",
    sourceName: "Projects_Aqua Properties.jpeg",
  },
  "projects__building_nation": {
    category: "projects",
    order: 15,
    createdAt: "2026-03-19T12:26:34",
    sourceName: "Projects_Building Nation_2.jpeg",
  },
  "projects__tik_tok": {
    category: "projects",
    order: 16,
    createdAt: "2026-03-19T12:26:35",
    sourceName: "Projects_TikTok_2.jpeg",
  },
  "projects__chat_gpt": {
    category: "projects",
    order: 17,
    createdAt: "2026-03-19T12:26:36",
    sourceName: "Projects_ChatGPT_2.jpeg",
  },
  "projects__facebook": {
    category: "projects",
    order: 18,
    createdAt: "2026-03-19T12:26:36",
    sourceName: "Projects_Facebook.jpeg",
  },
  "projects__humanoid": {
    category: "projects",
    order: 19,
    createdAt: "2026-03-19T12:26:37",
    sourceName: "Projects_Humanoid.jpeg",
  },
  "projects__neura_link": {
    category: "projects",
    order: 20,
    createdAt: "2026-03-19T12:26:38",
    sourceName: "Projects_NeuraLink.jpeg",
  },
  "projects__bitcoin": {
    category: "projects",
    order: 21,
    createdAt: "2026-03-19T12:26:40",
    sourceName: "Projects_Bitcoin.jpeg",
  },
  "projects__coding_python": {
    category: "projects",
    order: 22,
    createdAt: "2026-03-19T12:26:40",
    sourceName: "Projects_Coding - Python.jpeg",
  },
  "projects__clash_of_royale": {
    category: "projects",
    order: 23,
    createdAt: "2026-03-19T12:26:41",
    sourceName: "Projects_Clash Of Royale.jpeg",
  },
  "projects__google_search": {
    category: "projects",
    order: 24,
    createdAt: "2026-03-19T12:26:42",
    sourceName: "Projects_Google Search_2.jpeg",
  },

  // religion
  "religion__ancient_egypt": {
    category: "religion",
    order: 1,
    createdAt: "2026-03-19T11:54:30",
    sourceName: "Religion_Ancient Egypt.jpeg",
  },
  "religion__greek_mythology": {
    category: "religion",
    order: 2,
    createdAt: "2026-03-19T11:54:32",
    sourceName: "Religion_Greek Mythology.jpeg",
  },
  "religion__indigenous_african": {
    category: "religion",
    order: 3,
    createdAt: "2026-03-19T11:54:35",
    sourceName: "Religion_Indigenous African.jpeg",
  },
  "religion__shinto": {
    category: "religion",
    order: 4,
    createdAt: "2026-03-19T11:54:35",
    sourceName: "Religion_Shinto.jpeg",
  },
  "religion__atheism": {
    category: "religion",
    order: 5,
    createdAt: "2026-03-19T11:54:36",
    sourceName: "Religion_Atheism.jpeg",
  },
  "religion__hinduism": {
    category: "religion",
    order: 6,
    createdAt: "2026-03-19T11:54:37",
    sourceName: "Religion_Hinduism.jpeg",
  },
  "religion__buddhism": {
    category: "religion",
    order: 7,
    createdAt: "2026-03-19T11:54:39",
    sourceName: "Religion_Buddhism.jpeg",
  },
  "religion__spiritualism": {
    category: "religion",
    order: 8,
    createdAt: "2026-03-19T11:54:40",
    sourceName: "Religion_Spiritualism.jpeg",
  },
  "religion__jainism": {
    category: "religion",
    order: 9,
    createdAt: "2026-03-19T11:54:42",
    sourceName: "Religion_Jainism.jpeg",
  },
  "religion__confucianism": {
    category: "religion",
    order: 10,
    createdAt: "2026-03-19T11:54:43",
    sourceName: "Religion_Confucianism.jpeg",
  },
  "religion__taoism": {
    category: "religion",
    order: 11,
    createdAt: "2026-03-19T11:54:45",
    sourceName: "Religion_Taoism.jpeg",
  },
  "religion__christianity": {
    category: "religion",
    order: 12,
    createdAt: "2026-03-19T11:54:46",
    sourceName: "Religion_Christianity.jpeg",
  },
  "religion__islam": {
    category: "religion",
    order: 13,
    createdAt: "2026-03-19T11:54:47",
    sourceName: "Religion_Islam.jpeg",
  },
  "religion__judaism": {
    category: "religion",
    order: 14,
    createdAt: "2026-03-19T11:54:48",
    sourceName: "Religion_Judaism.jpeg",
  },
  "religion__sikhism": {
    category: "religion",
    order: 15,
    createdAt: "2026-03-19T11:54:51",
    sourceName: "Religion_Sikhism.jpeg",
  },
  "religion__baha_i_faith": {
    category: "religion",
    order: 16,
    createdAt: "2026-03-19T11:54:52",
    sourceName: "Religion_Baha'i Faith.jpeg",
  },
  "religion__zoroastrianism": {
    category: "religion",
    order: 17,
    createdAt: "2026-03-19T11:54:52",
    sourceName: "Religion_Zoroastrianism.jpeg",
  },
};
